### ISSUE TITLE
Many thanks. Issue with wifi

### ISSUE THREAD

**Issue by Goller64** [Baio1977/Lenovo-Thinkpad-T14-#1]
tired your EFI folder with both Big Sur, where the wifi is there, but can not see any networks. And with Monteray, where i can see networks, but when i put in the wifi password to connect, the operating system then reboots. Can i give you any help in pinning this issue down.

**Comment by Baio1977** [comment]
have you adapted the WI-FI and BT kext to the OS in use ???
[](https://github.com/Baio1977/OC-Little-Translated/tree/main/10_Kexts_Loading_Sequence_Examples)
